In [1]:
%config IPCompleter.greedy=True

In [2]:
import argparse
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
if __name__ == '__main__':
    # Argument parser to parse command line arguments
    parser = argparse.ArgumentParser()

    parser.add_argument('--dataset', dest='dataset_path', action='store', type=str, help='path to dataset')
    parser.add_argument('--mode', dest='mode', action='store', type=str, help='mode of algorithm', default='erm')

#     args = parser.parse_args('--dataset /home/rmodi/Documents/20_Spring/CSE512/hw1/Breast_cancer_data.csv --mode erm'.split())
#     args = parser.parse_args('--dataset /home/rmodi/Documents/20_Spring/CSE512/hw1/Breast_cancer_data.csv --mode cfv'.split())
    args = parser.parse_args('--dataset /home/rmodi/Documents/20_Spring/CSE512/hw1/linearly-separable-dataset.csv --mode erm'.split())
#     args = parser.parse_args('--dataset /home/rmodi/Documents/20_Spring/CSE512/hw1/linearly-separable-dataset.csv --mode cfv'.split())

    # Get the filenames for the training and testing data along with the filenames of their target values data
    train_file, test_file = str(args.train_dataset), str(args.test_dataset)
    y_train_file, y_test_file = train_file.replace('.csv', '_label.csv'), test_file.replace('.csv', '_label.csv')
    # Get the dataframes for training and testing data
    X_train, X_test, y_train, y_test = train_test_split(train_file, test_file, y_train_file, y_test_file)

    # Create a ID3DecisionTree model and fit the model for the given training data
    model = ID3DecisionTree(args.p_value_threshold).fit(X_train, y_train)
    model.save(args.decision_tree)  # Save the model at the specified location

    preds = model.predict(X_test)  # Get the predictions for the test dataset
    preds.to_csv(args.output_file, header=False, index=False)  # Write the predictions to the output file

    print('Number of internal nodes: {} \nNumber of leaf nodes: {}'.format(model.internal_nodes_count,
                                                                           model.leaf_nodes_count))
    if y_test is not None:
        accuracy = accuracy_score(y_test, preds)  # Calculate accuracy if the target values for test data is given
        print('Model Accuracy: {}'.format(accuracy))


AttributeError: 'Namespace' object has no attribute 'train_dataset'

In [65]:
df = pd.read_csv(args.dataset_path)

In [66]:
df.head()

x1        x2  y
0  0.876607  3.007882  1
1  0.229373  0.661393  0
2  0.241416  1.610415  1
3  0.831164  1.879528  0
4  0.309244  0.663247  0

In [81]:
y = df.iloc[:, -1].values
y = np.where(y == 0, -1, 1)

In [82]:
y.shape

(1151,)

In [83]:
X = df.iloc[:, :-1]
X['bias'] = 1
X = X.values

In [84]:
X.shape

(1151, 3)

In [85]:
X

array([[0.8766075 , 3.00788153, 1.        ],
       [0.22937269, 0.66139291, 1.        ],
       [0.24141585, 1.61041534, 1.        ],
       ...,
       [0.11625614, 0.94551889, 1.        ],
       [0.74495011, 1.12962314, 1.        ],
       [0.22731161, 1.41663829, 1.        ]])

In [130]:
def train(X, y):
    w = np.zeros((X.shape[1],))
    i = 0
    MAX_ITERATIONS = 100_000
    while i < MAX_ITERATIONS:
        dot_product = y * np.dot(X, w)
        if np.any(dot_product <= 0):
            for idx in np.where(dot_product <= 0)[0]:
                w = w + y[idx] * X[idx]
            i += 1
        else:
            break
    return w

In [127]:
def error(X, y, w):
    return len(np.where(y * np.dot(X, w) <= 0)[0])

In [38]:
w

array([268737.27999955, -42312.46999846, -16579.02000024,  -2945.80000004,
       -12261.55284011,  25274.        ])

In [33]:
true_error = len(np.where(y * np.dot(X, w) <= 0)[0])

In [34]:
def

257

In [39]:
m = X.shape[0]

In [40]:
k = 10

In [41]:
s = int(m/k)

In [49]:
batches = []
for i in range(k):
    start_index, end_index = s*i, s*(i+1)
    if i < (k-1):
        batches.append((X[start_index:end_index], y[start_index:end_index]))
    else:
        batches.append((X[start_index:], y[start_index:]))

In [129]:
weights, errors = [], []
for i in range(k):
    train_X, train_y, test_X, test_y = None, None, None, None
    for j, (X, y) in enumerate(batches):
        if j == i:
            test_X, test_y = X, y
        else:
            if train_X is None:
                train_X, train_y = X, y
            else:
                train_X, train_y = np.append(train_X, X, axis=0), np.append(train_y, y)
    print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)
    weights.append(train(train_X, train_y))
    errors.append(error(test_X, test_y, weights[-1]))

(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(513, 6) (513,) (56, 6) (56,)
(513, 6) (513,)
(504, 6) (504,) (65, 6) (65,)
(504, 6) (504,)


In [131]:
weights

[array([ 1602637.45498681, -1247268.25006665,  1628099.43005266,
         -204412.19999828,   -59284.70236942,   191473.        ]),
 array([ 2061219.55899115, -1489749.3300563 ,  1841053.93003564,
         -287797.499992  ,   -81079.01394892,   243417.        ]),
 array([ 2047713.44498159, -1360180.17003455,  1739391.33005863,
         -226420.59999183,   -80136.07178945,   253555.        ]),
 array([ 2009539.39298381, -1416394.85005213,  1769030.36007114,
         -280931.69998831,   -81102.31230948,   228800.        ]),
 array([ 1944952.22598135, -1849668.45006975,  1883146.68005439,
         -285094.19999497,   -80257.83340868,   236207.        ]),
 array([ 2122866.92897787, -1533106.42006614,  1877690.9600713 ,
         -296382.49999435,   -82754.275769  ,   257613.        ]),
 array([ 1985263.04199866, -1375389.07004903,  1778656.9600699 ,
         -285086.39999348,   -79784.25563902,   244951.        ]),
 array([ 2049833.86696853, -1561224.00004747,  1808875.69007162,
         -2

In [133]:
np.mean(errors)

13.1

In [125]:
w

array([151893.0080001 , -89538.88000133, 169260.5800028 , -26270.40000008,
        -4187.06775   ,  19006.        ])